var n1 = 1;
var n2 = 2;
var test = false;
console.log("The current value of n1 is: " + n1);
console.log("The current value of n1 is: " + n2);
console.log("\n\n");
console.log("True/False Statements");
console.log("---------------------");
test = n1 > n2;
console.log("n1 has a greater value than n2: " + "That is " + test);
test = n1 < n2;
console.log("n1 has a smaller value than n2: " + "That is " + test);
test = n1 == n2;
console.log("n1 is equal to n2: " + "That is " + test);
console.log("\n\n");
